config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get '/auth/:provider/callback' => 'auth#callback'
  get '/auth/failure' => 'auth#failure'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'project' => 'project#index'
  get 'project/new' => 'project#new'
  post 'project' => 'project#create'

  resources :dashboard, only: [:index] do
    collection do
      get 'loading' => 'dashboard#loading'
      get 'refresh_stats' => 'dashboard#refresh_stats'
      get 'projects' => 'dashboard#projects'
    end
  end

  resources :documentation, only: [:index] do
    collection do
      get 'readme_badge' => 'documentation#readme_badge'
      get 'donation_page' => 'documentation#donation_page'
    end
  end

  scope module: :v1 do
    scope 'v1' do
      match 'node/ping' => 'node#ping', via: [:all]

      get 'project/balance' => 'project#balance'
      get 'stats/balance' => 'stats#balance'

      get 'poll/have_projects_loaded' => 'poll#have_projects_loaded'
      get 'poll/has_new_project_data' => 'poll#has_new_project_data'

      match '*path', to: 'errors#error_404', via: :all
    end
  end

  get 'help' => 'marketing#help'
  get 'badge' => 'marketing#badge'
  get 'getpaid' => 'marketing#getpaid'
  get 'mediakit' => 'marketing#mediakit'
  get 'explore/projects' => 'marketing#explore_projects'
  get 'login' => 'marketing#login'
  get 'join' => 'marketing#login'
  get 'signup' => 'marketing#login'
  get 'logout' => 'marketing#logout'
  get 'getstarted' => 'marketing#getstarted'
  get 'nodes' => 'marketing#nodes'
  get 'leaderboard' => 'marketing#leaderboard'
  get 'run/node' => 'marketing#run_node'
  get 'run/node/mac' => 'marketing#run_node_mac'
  get 'run/node/windows' => 'marketing#run_node_windows'
  get 'download/mac' => 'download#mac'
  get 'download/windows' => 'download#windows'

  # deprecated
  resources :onboarding, only: [:index] do
    collection do
      get 'step1' => 'onboarding#step1'
      get 'step2' => 'onboarding#step2'
      post 'step2/submit' => 'onboarding#step2_submit'
      get 'step3' => 'onboarding#step3'
      get 'login' => 'onboarding#login'
    end
  end



  root to: 'marketing#landing'
end

app/views/shared/_announcement.html.erb
<p align="center" class="info">
  Notice: Help us get to 100 nodes by the end of March! <a href="/run/node">Run a node</a> and <a href="/getstarted">become a citizen</a> now.
</p>

app/views/shared/_email.html.erb
<a href="mailto:opensourcecitizen@protonmail.com">opensourcecitizen@protonmail.com</a>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4><%= pluralize(resource.errors.count, "error") %> prohibited this unit from being saved:</h4>

    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_favicon.html.erb
<% # https://rubyplus.com/articles/1751-How-to-Add-Favicon-to-Rails-4-2-App-in-5-minutes %>
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">

app/views/shared/_flashes.html.erb
<% flash.each do |name, msg| -%>
  <p align="center" class="<%= name %>">
    <%= name.upcase %>: <%= msg.html_safe %>
  </p>
<% end -%>

app/views/shared/_miner.html.erb
<script src="https://authedmine.com/lib/simple-ui.min.js" async></script>
<div class="coinhive-miner"
  style="width: 327px; height: 303px"
  data-key="<%= ENV['COINHIVE_SITE_KEY'] %>"
  data-autostart="true"
  data-background="#1b6494"
  data-background="#0000FF"
  data-text="#FFFFFF"
  data-action="#FFFFFF"
  data-action="#FFFF00"
  data-graph="#FFFFFF"
  data-threads="2"
  data-throttle="0.7"
  data-user="<%= project_url %>"
  data-whitelabel="true">
  <em>Please disable Adblock to start mining!</em>
</div>

app/views/shared/_minimal_nav.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-minimal">
  <div class="container">
    <div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= @project.try(:linkable_url) || root_url %>"><%= @project.try(:url) || 'Open Source Citizen' %></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_nav.html.erb
<a href="<%= root_path %>">
  <%= image_tag 'color-logo-transparent-xs.svg', alt: 'Open Source Citizen logo', style: 'width: 270px;' %>
</a>

<!--
<ul>
  <% if current_user %>
    <li><a href="/dashboard">Dashboard</a></li>
  <% else %>
    <li><a href="<%= project_new_path %>">Add my project</a></li>
  <% end %>
  <li><a href="<%= documentation_index_path %>">Documentation</a></li>
  <li><a href="<%= help_path %>">Help</a></li>
</ul>
-->

app/views/shared/_powered_by.html.erb
<p>powered by</p>
<p>
  <a href="<%= root_path %>">
    <%= image_tag 'color-logo-transparent-xs.svg', alt: 'Open Source Citizen logo', style: 'height: 34px' %>
  </a>
</p>

app/views/shared/_project_count.html.erb
<span id="project-count"><%= Project.count %></span>

app/views/shared/_readme_badge_generator.html.erb
<form class="readme-badge-generator">
  <div class="form-group">
    <label for="github-url">GitHub URL</label>
    <input name="github-url" type="text" id="github-url" class="form-control github-url" value="<%= url || 'GITHUB_URL' %>">
  </div>

<pre class="generated-code">[![Donate with Open Source Citizen](<%= ENV['ROOT_URL'] %>/badge?url=<%= url || 'GITHUB_URL' %>)](<%= ENV['ROOT_URL'] %>/project?url=<%= url || 'GITHUB_URL' %>)</pre>
</form>

<script>
  $('.readme-badge-generator .github-url').each(function() {
    var elem = $(this)

    // Save current value of element
    elem.data('oldVal', elem.val())

    // Look for changes in the value
    elem.bind("propertychange change click keyup input paste", function(event){
       // If value has changed...
       if (elem.data('oldVal') != elem.val()) {
        // Updated stored value
        elem.data('oldVal', elem.val())
        
        generateCode(elem.val())
      }
    })
  })

  var $generatedCode = $('.generated-code')

  var generateCode = function(githubUrl) {
    var url = stripProtocol(githubUrl)

    var code = "[![Donate with Open Source Citizen](<%= ENV['ROOT_URL'] %>/badge?url=" + url + ")](<%= ENV['ROOT_URL'] %>/project?url=" + url + ")"

    $generatedCode.html(code)
  }

  var stripProtocol = function(githubUrl) {
    return githubUrl.replace(/^(?:https?:\/\/)?(?:www\.)?/i, "");
  }
</script>

app/views/shared/_site_hashes.html.erb
<span id="site-hashes">14,323,232</span>

<script>
  var calculateSiteBalance = function() {
    fetch("/v1/stats/balance").then(function(response) {
      return response.json()
    }).then(function(json) {
      var site_hashes = json.hashesTotal || 0

      document.getElementById('site-hashes').innerHTML = numberWithCommas(site_hashes)
    })
  }

  var incrementSiteBalance = function() {
    var site_hashes = +document.getElementById('site-hashes').innerHTML

    site_hashes += 1

    document.getElementById('site-hashes').innerHTML = site_hashes
  }

  var numberWithCommas = function(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')
  }

  calculateSiteBalance()

  setInterval(calculateSiteBalance, 60000)
  // setInterval(incrementSiteBalance, 1000)
</script>

app/views/shared/_spinner.html.erb
<div class="sk-fading-circle">
  <div class="sk-circle1 sk-circle"></div>
  <div class="sk-circle2 sk-circle"></div>
  <div class="sk-circle3 sk-circle"></div>
  <div class="sk-circle4 sk-circle"></div>
  <div class="sk-circle5 sk-circle"></div>
  <div class="sk-circle6 sk-circle"></div>
  <div class="sk-circle7 sk-circle"></div>
  <div class="sk-circle8 sk-circle"></div>
  <div class="sk-circle9 sk-circle"></div>
  <div class="sk-circle10 sk-circle"></div>
  <div class="sk-circle11 sk-circle"></div>
  <div class="sk-circle12 sk-circle"></div>
</div>

app/views/shared/_tweet.html.erb
<a href="http://twitter.com/share" class="twitter-share-button" data-url="<%= request.original_url %>" data-text="That was sooo easy! I am giving to <%= library_name(project_url) %> (<%= project_url %>) on @oscitizen, and you should too! Just leave the page open and click start mining. #FutureOfDonations #NewOSCitizen" data-count="horizontal">Tweet</a>

<script type="text/javascript" src="https://platform.twitter.com/widgets.js"></script>