config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get '/auth/:provider/callback' => 'auth#callback'
  get '/auth/failure' => 'auth#failure'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'project' => 'project#index'
  get 'project/new' => 'project#new'
  post 'project' => 'project#create'

  resources :dashboard, only: [:index] do
    collection do
      get 'loading' => 'dashboard#loading'
      get 'refresh_stats' => 'dashboard#refresh_stats'
      get 'projects' => 'dashboard#projects'
    end
  end

  resources :documentation, only: [:index] do
    collection do
      get 'readme_badge' => 'documentation#readme_badge'
      get 'donation_page' => 'documentation#donation_page'
    end
  end

  scope module: :v1 do
    scope 'v1' do
      match 'node/ping' => 'node#ping', via: [:all]

      get 'project/balance' => 'project#balance'
      get 'stats/balance' => 'stats#balance'

      get 'poll/have_projects_loaded' => 'poll#have_projects_loaded'
      get 'poll/has_new_project_data' => 'poll#has_new_project_data'

      match '*path', to: 'errors#error_404', via: :all
    end
  end

  get 'help' => 'marketing#help'
  get 'badge' => 'marketing#badge'
  get 'getpaid' => 'marketing#getpaid'
  get 'mediakit' => 'marketing#mediakit'
  get 'explore/projects' => 'marketing#explore_projects'
  get 'login' => 'marketing#login'
  get 'join' => 'marketing#login'
  get 'signup' => 'marketing#login'
  get 'logout' => 'marketing#logout'
  get 'getstarted' => 'marketing#getstarted'
  get 'nodes' => 'marketing#nodes'
  get 'leaderboard' => 'marketing#leaderboard'
  get 'run/node' => 'marketing#run_node'
  get 'run/node/mac' => 'marketing#run_node_mac'
  get 'run/node/windows' => 'marketing#run_node_windows'
  get 'download/mac' => 'download#mac'
  get 'download/windows' => 'download#windows'

  # deprecated
  resources :onboarding, only: [:index] do
    collection do
      get 'step1' => 'onboarding#step1'
      get 'step2' => 'onboarding#step2'
      post 'step2/submit' => 'onboarding#step2_submit'
      get 'step3' => 'onboarding#step3'
      get 'login' => 'onboarding#login'
    end
  end



  root to: 'marketing#landing'
end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController
  def leaderboard
    RegenerateLeaderboard.perform_later

    @users = User.where('hashes_count IS NOT NULL').order('hashes_count DESC') 
  end

  def nodes
    @nodes = Node.order('pinged_at DESC, created_at DESC') 
  end

  def badge
    send_file 'public/badges/3.svg', type: 'image/svg+xml', disposition: 'inline'
  end

  def explore_projects
    @projects = Project.all
  end

  def logout
    clear_current_user

    redirect_to request.base_url
  end
end

app/views/marketing/documentation.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Documentation</h1>

      <h2>Access</h2>

      <p>
        To use any of OSC's services, you have to <a href="<%= project_new_path %>">add your project</a>. A donation page will be generated for your project. Here is an <a href="<%= project_path(url: 'github.com/motdotla/dotenv') %>">example</a>.
      </p>

      <div class="row">
        <div class="col-md-6">
          <h2>Donation page</h2>

          <p>The easiest way to get started with OSC and let users start donating to your project.</p>

          <p>
            <%= link_to 'view', documentation_donation_page_path %>
          </p>
        </div>

        <div class="col-md-6">
          <h2>README badge</h2>
        </div>

        <div class="col-md-6">
          <h2>Chrome plugin</h2>
        </div>

        <div class="col-md-6">
          <h2>Fair payouts</h2>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/marketing/explore_projects.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Explore Projects</h1>

      <ul>
        <% @projects.each do |project | %>
          <li>
            <%= link_to project.url, project_path(url: project.url) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<br/>
<br/>

<%= render 'shared/add_your_project_jumbo' %>

app/views/marketing/getpaid.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Get Paid</h1>

      <p>
        We are actively working on automating the payment process. Until then, please contact us at <a href="mailto:opensourcecitizen@protonmail.com">opensourcecitizen@protonmail.com</a> to claim your earnings.
      </p>

      <p>
        We will verify you as the owner of the project and send the Monero to you - which you can convert to USD or any currency you prefer.
      </p>

      <p>
        You can tell how much your project(s) have earned by visiting their pages. The minimum payout threshold is 0.05 XMR.
      </p>
    </div>
  </div>
</div>

app/views/marketing/getstarted.html.erb
<h1>Become a Citizen</h1>

<dl>
  <dt>
    <a href="/auth/github">Join with GitHub</a>
    <dd>Use your GitHub identity</dd>
  </dt>
  <dt>
    <a href="/auth/bitbucket">Join with Bitbucket</a>
    <dd>Use your Bitbucket identity</dd>
  </dt>
</dl>

app/views/marketing/help.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Help</h1>

      <p>Table of Contents</p>

      <ul>
        <li>
          <a href="/help#how-does-it-work">How does it work?</a>
        </li>
        <li>
          <a href="/help#get-paid">How do I get paid?</a>
        </li>
        <li>
          <a href="/help#readme-badge">Is there a readme badge?</a>
        </li>
        <li>
          <a href="/help#claim">How do I claim my project donations?</a>
        </li>
        <li>
          <a href="/help#media-kit">Do you have a media kit?</a>
        </li>
        <li>
          <a href="/help#contact">Get in touch</a>
        </li>
      </ul>

      <br/>

      <h3 id="how-does-it-work">How does it work?</h3>

      <p><a href="<%= project_new_path %>">Add your project</a> to create a shareable donation page. Your users visit that page and mine cryptocurrency on your project's behalf. All they have to do is push a button.</p>

      <h3 id="get-paid">How do I get paid?</h3>

      <p>Every $10 you earn pays you out in Monero. For now, payment is made by contacting <a href="mailto:opensourcecitizen@protonmail.com">opensourcecitizen@protonmail.com</a>.</p>

      <h3 id="readme-badge">Is there a readme badge?</h3>

      <p>Yes! If you use Open Source Citizen for your project, you can include one of these badges in your readme to let people know they can donate to your project using Open Source Citizen.</p>

      <%= render 'shared/readme_badge', url: 'opensourcecitizen.org' %>

      <h3 id="claim">How do I claim my project donations?</h3>

      <p>We are working on more automated ways to claim your donations. Meanwhile, just contact us at <a href="mailto:opensourcecitizen@protonmail.com">opensourcecitizen@protonmail.com</a> and we will process your claim.</p>

      <h3 id="media-kit">Do you have a media kit?</h3>

      <p>Yes. <a href="<%= mediakit_path %>">Click here</a> to view the <a href="<%= mediakit_path %>">Open Source Citizen Media Kit</a>.</p>

      <h3 id="contact">Get in touch</h3>

      <p>Contact us at <a href="mailto:opensourcecitizen@protonmail.com">opensourcecitizen@protonmail.com</a>. We'd love to hear from you and can answer any other questions you have.</p>
    </div>
  </div>
</div>

app/views/marketing/landing-draft1.html.erb
<h1>Earn money for your open source projects. No credit card, no bank account needed.</h1>

<!-- <p>Users donate to open source software by mining cryptocurrency.</p> -->

<p>Users contribute their CPU cycles and you get paid in <a href="https://www.monero.how/why-monero-vs-bitcoin">Monero</a>.</p>

<h2 class="text-center">How it works</h2>

<%= render 'shared/miner', project_url: 'opensourcecitizen.org' %>

<p>Click 'Start Mining' above. That's it! Your donors don't have to enter a credit card. They don't even need a bank account. And they can be from anywhere in the world. 🌍</p>

<p>It is the easiest way for people to donate to open source software. <strong>Add your project and start earning today.</strong></p>

<h1>Add your project</h1>

<h2>1. Generate your project link</h2>

<p>
  <strong>Your project's repository url:</strong>
  <%= text_field_tag :project_url, nil, placeholder: 'github.com/username/project', id: 'project_url_input' %>
</p>

<button type="link" id="button">Generate project link ↓</button>

<pre id="link">Your link will appear here!</pre>

<h2>2. Copy and paste the link on another tab for testing</h2>

<p>You can try this link in another tab before you share it.</p>

<h2>3. Share the link</h2>

<p>Now your users can contribute to your project by donating hashes and you can earn Monero.</p>

<p>
  <a id="link2" href="" target="_blank"></a>
</p>

<script>
  var link = document.getElementById('link')
  var link2 = document.getElementById('link2')
  var button = document.getElementById('button')
  var project_url_input = document.getElementById('project_url_input')

  button.addEventListener('click', function() {
    var ready_url = "<%= ENV['ROOT_URL'] %>/project?url=" + project_url_input.value

    link.innerHTML = ready_url
    link2.innerHTML = ready_url
    link2.href = ready_url
  })
</script>

<h1>
  Stats
</h1>

<h2>
  Hashes: <%= render 'shared/site_hashes' %>
</h2>

<h2>
  Projects: <%= render 'shared/project_count' %>
</h2>

<h1>
  Quotes
</h1>

<p>
  Add quotes from people talking about how great it is. and how it has helped pay for their open source.
</p>

<h1>
  Awesome projects
</h1>

<p>
  List awesome projects already using Give a Hash
</p>

<h1>Add your project</h1>

<p>
  Intersperse a simpler form to add your project
</p>

<h1>Team</h1>

<p>
  Show the team behind the project.
</p>

<h1>Footer</h1>

<p>
  Add footer nav with more info. Fill this out over time with more and more links to useful info, to display legitimacy.
</p>

app/views/marketing/landing.html.erb
<p>
  Open Source Citizen (OSC) is an economic citizenship experiment aiming to increase economic participation in open source software.
</p>

<p>
  Find everything you need to get started below.
</p>

<dl>
  <dt>
    <a href="/getstarted">Become a Citizen</a>
    <dd>Use your GitHub or Bitbucket account to become a citizen.</dd>
  </dt>

  <dt>
    <a href="/run/node">Run a Node</a>
    <dd>Run a node to contribute economically</dd>
  </dt>

  <dt>
    <a href="/nodes">Nodes</a>
    <dd>List of nodes and their statuses</dd>
  </dt>

  <dt>
    <a href="/dashboard">My Citizenship</a>
    <dd>Manage your citizenship - economic contributions and profits.</dd>
  </dt>

	<% if current_user %>
		<dt>
			<a href="/logout">Log out</a>
			<dd>
				End the current session
			</dd>
		</dt>
	<% else %>
		<dt>
			<a href="/login">Log in</a>
			<dd>If you have already joined as a citizen.</dd>
		</dt>
	<% end %>
</dl>

<!--

Those that create open source software should be rewarded for doing so.

Those who use open source software should 

But the nature of open source software is such that copying it is easy and as a result economic attribution often goes unattributed.

Furthermore, the nature of open source results in the most open of software being the most successsful. But part of being open is to be free. And so, often, the best software goes unrewarded when it becomes wildly successful.

Instead, this should be rewarded. 

Ideally, this should be rewarded with small micro payments. This is difficult to do with modern tools - except for cryptocurrencies.

<dl>
  <dt>
    <a href="/">Download</a>
    <dd>Download to get started</dd>
  </dt>
  <dt>
    <a href="/">How does it work?</a>
    <dd>Information on how it works</dd>
  </dt>
  <dt>
    <a href="/">Contribute</a>
    <dd>Instructions on how to easily contribute</dd>
  </dt>

  <dt>
    <a href="/">How do I become a citizen?</a>
    <dd>Information on becoming a citizen</dd>
  </td>
</dl>








        Open source citizen allows open source developers like you to get paid by running a <strong>cryptocurrency donation mining pool</strong> on behalf of your libraries.




Pointers to the world's online information, subjects , W3 servers, etc.
Help
on the browser you are using
Software Products
A list of W3 project components and their current state. (e.g. Line Mode ,X11 Viola , NeXTStep , Servers , Tools , Mail robot , Library )
Technical
Details of protocols, formats, program internals etc
Bibliography
Paper documentation on W3 and references.
People
A list of some people involved in the project.
History
A summary of the history of the project.
How can I help ?
If you would like to support the web..
Getting code
Getting the code by anonymous FTP , etc.

<h1><%= ENV['TAGLINE'] %></h1>

<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1><%= ENV['TAGLINE'] %></h1>

        <a class="btn btn-default btn-xlg btn-space btn-block-smart" href="#how-it-works" role="button">How it works</a>
        <a class="btn btn-success btn-xlg btn-space btn-block-smart" href="<%= project_new_path %>" role="button">Add my project</a>
      </div>
      <div class="col-md-5">
        <div class="pull-right-lg hero-miner">
          <%= render 'shared/miner', project_url: 'opensourcecitizen.org' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <p class="text-center catchphrase">
        Open source citizen allows open source developers like you to get paid by running a <strong>cryptocurrency donation mining pool</strong> on behalf of your libraries.
      </p>
    </div>
  </div>
</div>

<div id="how-it-works" class="container">
  <div class="row">
    <div class="col-sm-12">
      <h2 class="text-center">How It Works</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <h3 class="text-center">Step 1</h3>
      <a href="<%= project_new_path %>" class="thumbnail">
        <%= image_tag 'add-your-project-screenshot.png' %>
      </a>
      <p class="lead">
        Enter your GitHub project url. A donation page is automatically created for you and includes information on how to share the page.
      </p>
    </div>
    <div class="col-sm-4">
      <h3 class="text-center">Step 2</h3>
      <a href="<%= help_path %>" class="thumbnail">
        <%= image_tag 'readme-badge-screenshot.png' %>
      </a>
      <p class="lead">
        Place it on your README, tweet it out, or post it in your mailing list so that users can start donating CPU cycles.
      </p>
    </div>
    <div class="col-sm-4">
      <h3 class="text-center">Step 3</h3>
      <a href="<%= project_path(url: 'github.com/motdotla/dotenv') %>" class="thumbnail">
        <%= image_tag 'miner-running.gif' %>
      </a>
      <p class="lead">
        Users spare some CPU cycles, generating hashes, to give back to your project. They don't need a credit card, they don't even need a bank account.
      </p>
    </div>
  </div>
</div>

<!--
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="text-center">Projects earning on Open Source Citizen</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <strong>dotenv</strong> is a popular node library.
            <br/>
            Donors have contributes 800k hashes to its project and counting.
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <strong>dotenv</strong> is a popular node library.
            <br/>
            Donors have contributes 800k hashes to its project and counting.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
-->

<%#= render 'shared/add_your_project_jumbo' %>


<!--
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center"><%= render 'shared/site_hashes' %> hashes donated and counting!</h2>
      <h2 class="text-center">The community is currently donating <%= render 'shared/site_hash_rate' %> hashes/second.</h2>
    </div>
  </div>
</div>
-->

app/views/marketing/leaderboard.html.erb
<h1>Leaderboard (<%= @users.count %>)</h1>

<table width="100%">
  <caption>Organized by highest to lowest economic contributions per citizen.</caption>
  <thead>
    <tr class="w3-blue">
      <th>Position</th>
      <th>Citizen</th>
      <th>Economic Contributions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td>Citizen <%= user.id %></td>
        <td><%= number_with_delimiter user.hashes_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/marketing/login.html.erb
<h1>Login</h1>

<dl>
  <dt>
    <a href="/auth/github">Log in using GitHub</a>
    <dd>Use your GitHub identity</dd>
  </dt>
  <dt>
    <a href="/auth/bitbucket">Log in using Bitbucket</a>
    <dd>Use your Bitbucket identity</dd>
  </dt>
</dl>

app/views/marketing/mediakit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Media Kit</h1>

      <h3 id="graphics">Graphics</h3>

      <%= image_tag 'mediakit/svg/color_logo_transparent.svg', width: '300' %>

      <p>Click on the links below to download the specific logo you need.</p>

      <ul>
        <li>
          dark transparent:
          <%= link_to 'png', asset_path('mediakit/png/dark_logo_transparent@2x.png') %>
          <%= link_to 'svg', asset_path('mediakit/svg/dark_logo_transparent.svg') %>
        </li>
        <li>
          white transparent: 
          <%= link_to 'png', asset_path('mediakit/png/white_logo_transparent@2x.png') %>
          <%= link_to 'svg', asset_path('mediakit/svg/white_logo_transparent.svg') %>
        </li>
        <li>
          color transparent: 
          <%= link_to 'png', asset_path('mediakit/png/color_logo_transparent@2x.png') %>
          <%= link_to 'svg', asset_path('mediakit/svg/color_logo_transparent.svg') %>
        </li>
        <li>
          color white background: 
          <%= link_to 'png', asset_path('mediakit/png/color_with_background@2x.png') %>
          <%= link_to 'svg', asset_path('mediakit/svg/color_with_background.svg') %>
        </li>
      </ul>

      <h3 id="brand-guidelines">Brand Guidelines</h3>

      <p>See the <a href="https://logojoy.com/b/opensourcecitizen">brand guidelines</a> by clicking <a href="https://logojoy.com/b/opensourcecitizen">here</a>.</p>

      <!--
      <h3>Open Source Citizen description</h3>

      <p>Coming soon.</p>

      <h3>Short Open Source Citizen description</h3>

      <p>Coming soon.</p>
      -->
    </div>
  </div>
</div>

app/views/marketing/nodes.html.erb
<h1>Nodes (<%= @nodes.count %>)</h1>

<table width="100%">
  <caption>List of nodes and their individual statuses. Current time is <%= Time.now.utc.strftime('%b %e, %l:%M %p UTC') %></caption>
  <thead>
    <tr class="w3-blue">
      <th>Identifier</th>
      <th>Last seen</th>
    </tr>
  </thead>
  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><abbr title="<%= node.machine_id %>"><%= node.abbr_machine_id %></abbr></td>
        <td><%= node.last_seen_at.strftime('%b %e, %l:%M %p UTC') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/marketing/run_node.html.erb
<h1>Run a Node</h1>

<p>
  Running a node signals your economic participation as a citizen in the OSC network. You can run multiple nodes to increase your economic participation and raise your citizenship status.
</p>

<dl>
  <dt>
    <a href="/run/node/mac">Run on Mac</a>
    <dd>Download page with installation instructions</dd>
  </dt>
  <dt>
    Run on Linux
    <dd>Coming soon</dd>
  </dt>
  <dt>
    <a href="/run/node/windows">Run on Windows</a>
    <dd>Download page with installation instructions</dd>
  </dt>
  <dt>
    <a href="/nodes">Nodes</a>
    <dd>List of nodes and their statuses</dd>
  </dt>
</dl>

app/views/marketing/run_node_mac.html.erb
<h1>Mac Node</h1>

<dl>
  <dt>
    <a href="/download/mac">Download (mac)</a>
    <dd>Download to your machine</dd>
  </dt>
</dl>

<h3>Install Instructions</h3>

<ol>
  <li><a href="/download/mac">Download</a> and open the <a href="/download/mac">dmg</a> file</li>
  <li>Drag it to your Applications folder</li>
  <li>Double click it to run it</li>
</ol>

<p>If you are successful, you will see OSC running on your mac's menu bar.</p>

<h3>Usage Instructions</h3>

<p>Keep running at startup of your machine. It will run silently in the background, contributing economically to the OSC network.</p>

<p>You can monitor your economic contribution from your <a href="/dashboard">citizenship page</a>.</p>

app/views/marketing/run_node_windows.html.erb
<h1>Windows Node</h1>

<dl>
  <dt>
    <a href="/download/windows">Download (windows)</a>
    <dd>Download to your machine</dd>
  </dt>
</dl>

<h3>Install Instructions</h3>

<ol>
  <li><a href="/download/windows">Download</a> and open the <a href="/download/windows">exe</a> file</li>
  <li>Drag it to your Applications folder</li>
  <li>Double click it to run it</li>
</ol>

<p>If you are successful, you will see OSC running.</p>

<h3>Usage Instructions</h3>

<p>Keep running at startup of your machine. It will run silently in the background, contributing economically to the OSC network.</p>

<p>You can monitor your economic contribution from your <a href="/dashboard">citizenship page</a>.</p>