config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get '/auth/:provider/callback' => 'auth#callback'
  get '/auth/failure' => 'auth#failure'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'project' => 'project#index'
  get 'project/new' => 'project#new'
  post 'project' => 'project#create'

  resources :dashboard, only: [:index] do
    collection do
      get 'loading' => 'dashboard#loading'
      get 'refresh_stats' => 'dashboard#refresh_stats'
      get 'projects' => 'dashboard#projects'
    end
  end

  resources :documentation, only: [:index] do
    collection do
      get 'readme_badge' => 'documentation#readme_badge'
      get 'donation_page' => 'documentation#donation_page'
    end
  end

  scope module: :v1 do
    scope 'v1' do
      match 'node/ping' => 'node#ping', via: [:all]

      get 'project/balance' => 'project#balance'
      get 'stats/balance' => 'stats#balance'

      get 'poll/have_projects_loaded' => 'poll#have_projects_loaded'
      get 'poll/has_new_project_data' => 'poll#has_new_project_data'

      match '*path', to: 'errors#error_404', via: :all
    end
  end

  get 'help' => 'marketing#help'
  get 'badge' => 'marketing#badge'
  get 'getpaid' => 'marketing#getpaid'
  get 'mediakit' => 'marketing#mediakit'
  get 'explore/projects' => 'marketing#explore_projects'
  get 'login' => 'marketing#login'
  get 'join' => 'marketing#login'
  get 'signup' => 'marketing#login'
  get 'logout' => 'marketing#logout'
  get 'getstarted' => 'marketing#getstarted'
  get 'nodes' => 'marketing#nodes'
  get 'leaderboard' => 'marketing#leaderboard'
  get 'run/node' => 'marketing#run_node'
  get 'run/node/mac' => 'marketing#run_node_mac'
  get 'run/node/windows' => 'marketing#run_node_windows'
  get 'download/mac' => 'download#mac'
  get 'download/windows' => 'download#windows'

  # deprecated
  resources :onboarding, only: [:index] do
    collection do
      get 'step1' => 'onboarding#step1'
      get 'step2' => 'onboarding#step2'
      post 'step2/submit' => 'onboarding#step2_submit'
      get 'step3' => 'onboarding#step3'
      get 'login' => 'onboarding#login'
    end
  end



  root to: 'marketing#landing'
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
  def index
  end

  def donation_page
  end
end

app/views/documentation/donation_page.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1><a href="<%= documentation_index_path %>">Documentation</a> » Donation page</h1>

      <h2>Quickstart</h2>

      <p>
        <a href="<%= project_new_path %>" class="btn btn-large btn-success">Add project</a>
      </p>

      <h2>Overview</h2>

      <div class="pull-right documentation-miner-example">
        <%= render 'shared/miner', project_url: 'github.com/motdotla/dotenv' %>
        <p class="text-center"><em>Demo of the miner UI on a donation page.</em></p>
      </div>

      <p>This page explains how to create your project donation page.</p>

      <p>The project donation page loads a crypto currency miner as an iframe into a <code>&lt;div&gt;</code> element on your page. Donors click START MINING to mine for crypto currency in the browser.</p>

      <h2>Creating</h2>

      <p>Creating your donation page is easy.<p>
      <ol>
        <li> Click <a href="<%= project_new_path %>">add project</a></li>
        <li>Paste your project's GitHub URL</li>
        <li>Submit the form</li>
      </ol>

      <h2>Sharing</h2>

      <p>Share the url of your donation page by emailing it, tweeting it, or posting it on a mailing list. Donors click it and start mining.</p>

      <p>They can customize their CPU settings and leave the tab open for a day or two. If enough users do this, you will see some reasonable donation levels to help monetarily support your open source project.</p>

      <h2>Details</h2>

      <p>Sparing the minutiae, mining for crypto currency is a process of guessing a hash. To do this, your CPU generates thousands of hashes a minute.</p>

      <p>When you use <abbr title="Open Source Citizen">OSC</abbr>, you are combining the power of 10s to 1,000s of donors' machines to contribute to guessing that hash. The greater number of hashes generated, the greater your project's share in the donation pool. Therefore, the greater the amount of crypto currency your project will earn.</p>

      <p>If you have a popular open source library, your network is likely to be very large, and your potential for donations will also likely be large. But even if you have a less popular library, you stand to make a little extra money for your hard work and you also help spread the word about <abbr title="Open Source Citizen">OSC</abbr>. The more we can enable others to give back to open source the more open source can flourish.</p>

      <p><abbr title="Open Source Citizen">OSC</abbr> currently mines for the Monero Blockchain (<a href="#why-monero">Why Monero?</a>).</p>

      <h2 id="why-monero">Why Monero?</h2>

      <p>Monero uses a different mining algorithm than Bitcoin. It uses an algorithm called Cryptonight. It's a compute heavy algorithm and was designed to run well on consumer machines (Bitcoin does not run well on consumer machines).</p>

      <p>This makes Monero a great choice for donating since it evens the playing field - making it possible for normal developers with CPU based machines to donate back to a project they love at a relatively equal level.</p>
    </div>
  </div>

</div>

app/views/documentation/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Documentation</h1>

      <h2>Quickstart</h2>

      <p>
        To use <%= render 'shared/osc' %>, <a href="<%= project_new_path %>">add your project</a>. A donation page will be generated for your project. Here is an <a href="<%= project_path(url: 'github.com/motdotla/dotenv') %>">example</a>.
      </p>

      <div class="row">
        <div class="col-md-6">
          <h2><a href="<%= donation_page_documentation_index_path %>">Donation page</a></h2>

          <p>The easiest way to get started with <%= render 'shared/osc' %> and let users start donating to your project.</p>

          <p>
            <a href="<%= donation_page_documentation_index_path %>">view docs</a>
          </p>
        </div>

        <div class="col-md-6">
          <h2><a href="<%= readme_badge_documentation_index_path %>">README badge</a></h2>

          <p>The best way to alert developers to donate your to open source project.</p>

          <p>
            <a href="<%= readme_badge_documentation_index_path %>">view docs</a>
          </p>
        </div>

        <div class="col-md-6">
          <h2>Chrome plugin</h2>

          <p>The best way to maintain and support recurring donations from committed donors.</p>

          <p>Coming soon.</p>
        </div>

        <div class="col-md-6">
          <h2>Fair payouts</h2>

          <p>We are actively working on automating the payment process. Until then, please contact us at <%= render 'shared/email' %> to claim your earnings.</p>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/documentation/readme_badge.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1><a href="<%= documentation_index_path %>">Documentation</a> » README badge</h1>

      <h2>Quickstart</h2>

      <%= render 'shared/readme_badge_generator', url: 'github.com/motdotla/dotenv' %>

      <h2>Overview</h2>

      <p>This page explains how to create your README badge.</p>

      <p>The README badge provides a way to notify people that your project is accepting donations. They click on the README badge, which takes them to the <a href="<%= donation_page_documentation_index_path %>">donation page</a>.</p>

      <h2>Creating</h2>

      <p>Creating your README badge is easy.</p>

      <ol>
        <li>Replace <strong>GITHUB_URL</strong> with your project's GitHub url</li>
        <li>Paste the code into your README file</li>
      </ol>

<pre>[![Donate with Open Source Citizen](<%= ENV['ROOT_URL'] %>/badge?url=GITHUB_URL)](<%= ENV['ROOT_URL'] %>/project?url=GITHUB_URL)

If you found this library useful, donate some CPU cycles to its
development efforts by clicking above. Thank you! 😇</pre>

      <h2>Sharing</h2>

      <p>Paste the code into your README page. That's it!</p>
    </div>
  </div>
</div>